# Anna KaRNNa

In this notebook, we'll build a character-wise RNN trained on Anna Karenina, one of my all-time favorite books. It'll be able to generate new text based on the text from the book.

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Also, some information [here at r2rt](http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and from [Sherjil Ozair](https://github.com/sherjilozair/char-rnn-tensorflow) on GitHub. Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

In [40]:
import time
from collections import namedtuple

import numpy as np
import tensorflow as tf

First we'll load the text file and convert it into integers for our network to use. Here I'm creating a couple dictionaries to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [41]:
with open('anna.txt', 'r') as f:
    text=f.read()
vocab = sorted(set(text))
vocab_to_int = {c: i for i, c in enumerate(vocab)}
int_to_vocab = dict(enumerate(vocab))
encoded = np.array([vocab_to_int[c] for c in text], dtype=np.int32)

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [42]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

And we can see the characters encoded as integers.

In [43]:
encoded[:100]

array([31, 64, 57, 72, 76, 61, 74,  1, 16,  0,  0,  0, 36, 57, 72, 72, 81,
        1, 62, 57, 69, 65, 68, 65, 61, 75,  1, 57, 74, 61,  1, 57, 68, 68,
        1, 57, 68, 65, 67, 61, 26,  1, 61, 78, 61, 74, 81,  1, 77, 70, 64,
       57, 72, 72, 81,  1, 62, 57, 69, 65, 68, 81,  1, 65, 75,  1, 77, 70,
       64, 57, 72, 72, 81,  1, 65, 70,  1, 65, 76, 75,  1, 71, 79, 70,  0,
       79, 57, 81, 13,  0,  0, 33, 78, 61, 74, 81, 76, 64, 65, 70])

Since the network is working with individual characters, it's similar to a classification problem in which we are trying to predict the next character from the previous text.  Here's how many 'classes' our network has to pick from.

In [44]:
len(vocab)

83

## Making training mini-batches

Here is where we'll make our mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>
We have our text encoded as integers as one long array in `encoded`. Let's create a function that will give us an iterator for our batches. I like using [generator functions](https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/) to do this. Then we can pass `encoded` into this function and get our batch generator.

The first thing we need to do is discard some of the text so we only have completely full batches. Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences) and $M$ is the number of steps. Then, to get the number of batches we can make from some array `arr`, you divide the length of `arr` by the batch size. Once you know the number of batches and the batch size, you can get the total number of characters to keep.

After that, we need to split `arr` into $N$ sequences. You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences (`n_seqs` below), let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$ where $K$ is the number of batches.

Now that we have this array, we can iterate through it to get our batches. The idea is each batch is a $N \times M$ window on the array. For each subsequent batch, the window moves over by `n_steps`. We also want to create both the input and target arrays. Remember that the targets are the inputs shifted over one character. You'll usually see the first input character used as the last target character, so something like this:
```python
y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
```
where `x` is the input batch and `y` is the target batch.

The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of steps in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `n_steps` wide.

> **Exercise:** Write the code for creating batches in the function below. The exercises in this notebook _will not be easy_. I've provided a notebook with solutions alongside this notebook. If you get stuck, checkout the solutions. The most important thing is that you don't copy and paste the code into here, **type out the solution code yourself.**

In [45]:
def get_batches(arr, n_seqs, n_steps):
    '''Create a generator that returns batches of size
       n_seqs x n_steps from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       n_seqs: Batch size, the number of sequences per batch
       n_steps: Number of sequence steps per batch
    '''
    # Get the number of characters per batch and number of batches we can make
    characters_per_batch = n_seqs * n_steps
    n_batches = len(arr)//characters_per_batch
    
    # Keep only enough characters to make full batches
    arr = arr[:n_batches * characters_per_batch]
    
    # Reshape into n_seqs rows
    arr = arr.reshape((n_seqs, -1))
    
    for n in range(0, arr.shape[1], n_steps):
        # The features
        x = arr[:, n:n+n_steps]
        # The targets, shifted by one
        y = np.zeros_like(x)
        y[:, :-1], y[:, -1] = x[:, 1:], x[:, 0]
        yield x, y

Now I'll make my data sets and we can check out what's going on here. Here I'm going to use a batch size of 10 and 50 sequence steps.

In [46]:
batches = get_batches(encoded, 10, 50)
x, y = next(batches)

In [47]:
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[31 64 57 72 76 61 74  1 16  0]
 [ 1 57 69  1 70 71 76  1 63 71]
 [78 65 70 13  0  0  3 53 61 75]
 [70  1 60 77 74 65 70 63  1 64]
 [ 1 65 76  1 65 75 11  1 75 65]
 [ 1 37 76  1 79 57 75  0 71 70]
 [64 61 70  1 59 71 69 61  1 62]
 [26  1 58 77 76  1 70 71 79  1]
 [76  1 65 75 70  7 76 13  1 48]
 [ 1 75 57 65 60  1 76 71  1 64]]

y
 [[64 57 72 76 61 74  1 16  0  0]
 [57 69  1 70 71 76  1 63 71 65]
 [65 70 13  0  0  3 53 61 75 11]
 [ 1 60 77 74 65 70 63  1 64 65]
 [65 76  1 65 75 11  1 75 65 74]
 [37 76  1 79 57 75  0 71 70 68]
 [61 70  1 59 71 69 61  1 62 71]
 [ 1 58 77 76  1 70 71 79  1 75]
 [ 1 65 75 70  7 76 13  1 48 64]
 [75 57 65 60  1 76 71  1 64 61]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[55 63 69 22  6 76 45  5 16 35]
 [ 5 69  1  5 12 52  6  5 56 52]
 [48 29 12 61 35 35  8 64 76 78]
 [12  5 24 39 45 29 12 56  5 63]
 [ 5 29  6  5 29 78 28  5 78 29]
 [ 5 13  6  5 36 69 78 35 52 12]
 [63 76 12  5 18 52  1 76  5 58]
 [34  5 73 39  6  5 12 52 36  5]
 [ 6  5 29 78 12 79  6 61  5 59]
 [ 5 78 69 29 24  5  6 52  5 63]]

y
 [[63 69 22  6 76 45  5 16 35 35]
 [69  1  5 12 52  6  5 56 52 29]
 [29 12 61 35 35  8 64 76 78 28]
 [ 5 24 39 45 29 12 56  5 63 29]
 [29  6  5 29 78 28  5 78 29 45]
 [13  6  5 36 69 78 35 52 12 43]
 [76 12  5 18 52  1 76  5 58 52]
 [ 5 73 39  6  5 12 52 36  5 78]
 [ 5 29 78 12 79  6 61  5 59 63]
 [78 69 29 24  5  6 52  5 63 76]]
 ```
 although the exact numbers will be different. Check to make sure the data is shifted over one step for `y`.

## Building the model

Below is where you'll build the network. We'll break it up into parts so it's easier to reason about each bit. Then we can connect them up into the whole network.

<img src="assets/charRNN.png" width=500px>


### Inputs

First off we'll create our input placeholders. As usual we need placeholders for the training data and the targets. We'll also create a placeholder for dropout layers called `keep_prob`. This will be a scalar, that is a 0-D tensor. To make a scalar, you create a placeholder without giving it a size.

> **Exercise:** Create the input placeholders in the function below.

In [48]:
def build_inputs(batch_size, num_steps):
    ''' Define placeholders for inputs, targets, and dropout 
    
        Arguments
        ---------
        batch_size: Batch size, number of sequences per batch
        num_steps: Number of sequence steps in a batch
        
    '''
    # Declare placeholders we'll feed into the graph
    inputs = tf.placeholder(tf.int32, [batch_size, num_steps], name='inputs')
    targets = tf.placeholder(tf.int32, [batch_size, num_steps], name='targets')
    
    # Keep probability placeholder for drop out layers
    keep_prob = tf.placeholder(tf.float32, name='keep_prob')
    
    return inputs, targets, keep_prob

### LSTM Cell

Here we will create the LSTM cell we'll use in the hidden layer. We'll use this cell as a building block for the RNN. So we aren't actually defining the RNN here, just the type of cell we'll use in the hidden layer.

We first create a basic LSTM cell with

```python
lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
```

where `num_units` is the number of units in the hidden layers in the cell. Then we can add dropout by wrapping it with 

```python
tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
```
You pass in a cell and it will automatically add dropout to the inputs or outputs. Finally, we can stack up the LSTM cells into layers with [`tf.contrib.rnn.MultiRNNCell`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/rnn/MultiRNNCell). With this, you pass in a list of cells and it will send the output of one cell into the next cell. Previously with TensorFlow 1.0, you could do this

```python
tf.contrib.rnn.MultiRNNCell([cell]*num_layers)
```

This might look a little weird if you know Python well because this will create a list of the same `cell` object. However, TensorFlow 1.0 will create different weight matrices for all `cell` objects. But, starting with TensorFlow 1.1 you actually need to create new cell objects in the list. To get it to work in TensorFlow 1.1, it should look like

```python
def build_cell(num_units, keep_prob):
    lstm = tf.contrib.rnn.BasicLSTMCell(num_units)
    drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
    
    return drop
    
tf.contrib.rnn.MultiRNNCell([build_cell(num_units, keep_prob) for _ in range(num_layers)])
```

Even though this is actually multiple LSTM cells stacked on each other, you can treat the multiple layers as one cell.

We also need to create an initial cell state of all zeros. This can be done like so

```python
initial_state = cell.zero_state(batch_size, tf.float32)
```

Below, we implement the `build_lstm` function to create these LSTM cells and the initial state.

In [49]:
def build_lstm(lstm_size, num_layers, batch_size, keep_prob):
    ''' Build LSTM cell.
    
        Arguments
        ---------
        keep_prob: Scalar tensor (tf.placeholder) for the dropout keep probability
        lstm_size: Size of the hidden layers in the LSTM cells
        num_layers: Number of LSTM layers
        batch_size: Batch size

    '''
    ### Build the LSTM Cell
    # Use a basic LSTM cell    
    def build_cell(lstm_size, keep_prob):
        # Use a basic LSTM cell
        lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size)
        
        # Add dropout to the cell
        drop = tf.contrib.rnn.DropoutWrapper(lstm, output_keep_prob=keep_prob)
        return drop
            
    # Stack up multiple LSTM layers, for deep learning
    cell = tf.contrib.rnn.MultiRNNCell([build_cell(lstm_size, keep_prob) for _ in range(num_layers)])
    initial_state = cell.zero_state(batch_size, tf.float32)
    
    return cell, initial_state

### RNN Output

Here we'll create the output layer. We need to connect the output of the RNN cells to a full connected layer with a softmax output. The softmax output gives us a probability distribution we can use to predict the next character, so we want this layer to have size $C$, the number of classes/characters we have in our text.

If our input has batch size $N$, number of steps $M$, and the hidden layer has $L$ hidden units, then the output is a 3D tensor with size $N \times M \times L$. The output of each LSTM cell has size $L$, we have $M$ of them, one for each sequence step, and we have $N$ sequences. So the total size is $N \times M \times L$. 

We are using the same fully connected layer, the same weights, for each of the outputs. Then, to make things easier, we should reshape the outputs into a 2D tensor with shape $(M * N) \times L$. That is, one row for each sequence and step, where the values of each row are the output from the LSTM cells. We get the LSTM output as a list, `lstm_output`. First we need to concatenate this whole list into one array with [`tf.concat`](https://www.tensorflow.org/api_docs/python/tf/concat). Then, reshape it (with `tf.reshape`) to size $(M * N) \times L$.

One we have the outputs reshaped, we can do the matrix multiplication with the weights. We need to wrap the weight and bias variables in a variable scope with `tf.variable_scope(scope_name)` because there are weights being created in the LSTM cells. TensorFlow will throw an error if the weights created here have the same names as the weights created in the LSTM cells, which they will be default. To avoid this, we wrap the variables in a variable scope so we can give them unique names.

> **Exercise:** Implement the output layer in the function below.

In [50]:
def build_output(lstm_output, in_size, out_size):
    ''' Build a softmax layer, return the softmax output and logits.
    
        Arguments
        ---------
        
        lstm_output: List of output tensors from the LSTM layer
        in_size: Size of the input tensor, for example, size of the LSTM cells
        out_size: Size of this softmax layer
    
    '''

    # Reshape output so it's a bunch of rows, one row for each step for each sequence.
    # Concatenate lstm_output over axis 1 (the columns)
    seq_output = tf.concat(lstm_output, axis=1) 
    # Reshape seq_output to a 2D tensor with lstm_size columns
    x = tf.reshape(seq_output, [-1, in_size])
    
    # Connect the RNN outputs to a softmax layer
    with tf.variable_scope('softmax'):
        softmax_w = tf.Variable(tf.truncated_normal((in_size, out_size), stddev=0.1))
        softmax_b = tf.Variable(tf.zeros(out_size))
    
    # Since output is a bunch of rows of RNN cell outputs, logits will be a bunch
    # of rows of logit outputs, one for each step and sequence
    logits = tf.matmul(x, softmax_w) + softmax_b
    
    # Use softmax to get the probabilities for predicted characters
    out = tf.nn.softmax(logits, name='predictions')
    
    return out, logits

### Training loss

Next up is the training loss. We get the logits and targets and calculate the softmax cross-entropy loss. First we need to one-hot encode the targets, we're getting them as encoded characters. Then, reshape the one-hot targets so it's a 2D tensor with size $(M*N) \times C$ where $C$ is the number of classes/characters we have. Remember that we reshaped the LSTM outputs and ran them through a fully connected layer with $C$ units. So our logits will also have size $(M*N) \times C$.

Then we run the logits and targets through `tf.nn.softmax_cross_entropy_with_logits` and find the mean to get the loss.

>**Exercise:** Implement the loss calculation in the function below.

In [51]:
def build_loss(logits, targets, lstm_size, num_classes):
    ''' Calculate the loss from the logits and the targets.
    
        Arguments
        ---------
        logits: Logits from final fully connected layer
        targets: Targets for supervised learning
        lstm_size: Number of LSTM hidden units
        num_classes: Number of classes in targets
        
    '''
    
    # One-hot encode targets and reshape to match logits, one row per sequence per step
    y_one_hot = tf.one_hot(targets, num_classes)
    y_reshaped =  tf.reshape(y_one_hot, logits.get_shape())
    
    # Softmax cross entropy loss
    loss = tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=y_reshaped)
    loss = tf.reduce_mean(loss)
    return loss

### Optimizer

Here we build the optimizer. Normal RNNs have have issues gradients exploding and disappearing. LSTMs fix the disappearance problem, but the gradients can still grow without bound. To fix this, we can clip the gradients above some threshold. That is, if a gradient is larger than that threshold, we set it to the threshold. This will ensure the gradients never grow overly large. Then we use an AdamOptimizer for the learning step.

In [52]:
def build_optimizer(loss, learning_rate, grad_clip):
    ''' Build optmizer for training, using gradient clipping.
    
        Arguments:
        loss: Network loss
        learning_rate: Learning rate for optimizer
    
    '''
    
    # Optimizer for training, using gradient clipping to control exploding gradients
    tvars = tf.trainable_variables()
    grads, _ = tf.clip_by_global_norm(tf.gradients(loss, tvars), grad_clip)
    train_op = tf.train.AdamOptimizer(learning_rate)
    optimizer = train_op.apply_gradients(zip(grads, tvars))
    
    return optimizer

### Build the network

Now we can put all the pieces together and build a class for the network. To actually run data through the LSTM cells, we will use [`tf.nn.dynamic_rnn`](https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/nn/dynamic_rnn). This function will pass the hidden and cell states across LSTM cells appropriately for us. It returns the outputs for each LSTM cell at each step for each sequence in the mini-batch. It also gives us the final LSTM state. We want to save this state as `final_state` so we can pass it to the first LSTM cell in the the next mini-batch run. For `tf.nn.dynamic_rnn`, we pass in the cell and initial state we get from `build_lstm`, as well as our input sequences. Also, we need to one-hot encode the inputs before going into the RNN. 

> **Exercise:** Use the functions you've implemented previously and `tf.nn.dynamic_rnn` to build the network.

In [53]:
class CharRNN:
    
    def __init__(self, num_classes, batch_size=64, num_steps=50, 
                       lstm_size=128, num_layers=2, learning_rate=0.001, 
                       grad_clip=5, sampling=False):
    
        # When we're using this network for sampling later, we'll be passing in
        # one character at a time, so providing an option for that
        if sampling == True:
            batch_size, num_steps = 1, 1
        else:
            batch_size, num_steps = batch_size, num_steps

        tf.reset_default_graph()
        
        # Build the input placeholder tensors
        self.inputs, self.targets, self.keep_prob = build_inputs(batch_size, num_steps)

        # Build the LSTM cell
        cell, self.initial_state = build_lstm(lstm_size, num_layers, batch_size, keep_prob)

        ### Run the data through the RNN layers
        # First, one-hot encode the input tokens
        x_one_hot = tf.one_hot(self.inputs, num_classes)
        
        # Run each sequence step through the RNN with tf.nn.dynamic_rnn 
        outputs, state = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
        self.final_state = state
        
        # Get softmax predictions and logits
        self.prediction, self.logits = build_output(outputs, lstm_size, num_classes)
        
        # Loss and optimizer (with gradient clipping)
        self.loss =  build_loss(self.logits, self.targets, lstm_size, num_classes)
        self.optimizer = build_optimizer(self.loss, learning_rate, grad_clip)

## Hyperparameters

Here are the hyperparameters for the network.

* `batch_size` - Number of sequences running through the network in one pass.
* `num_steps` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lstm_size` - The number of units in the hidden layers.
* `num_layers` - Number of hidden LSTM layers to use
* `learning_rate` - Learning rate for training
* `keep_prob` - The dropout keep probability when training. If you're network is overfitting, try decreasing this.

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `lstm_size` and `num_layers`. I would advise that you always use `num_layers` of either 2/3. The `lstm_size` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `lstm_size` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.

In [54]:
batch_size = 10         # Sequences per batch
num_steps = 50          # Number of sequence steps per batch
lstm_size = 128         # Size of hidden layers in LSTMs
num_layers = 2          # Number of LSTM layers
learning_rate = 0.01    # Learning rate
keep_prob = 0.5         # Dropout keep probability

## Time for training

This is typical training code, passing inputs and targets into the network, then running the optimizer. Here we also get back the final LSTM state for the mini-batch. Then, we pass that state back into the network so the next batch can continue the state from the previous batch. And every so often (set by `save_every_n`) I save a checkpoint.

Here I'm saving checkpoints with the format

`i{iteration number}_l{# hidden layer units}.ckpt`

> **Exercise:** Set the hyperparameters above to train the network. Watch the training loss, it should be consistently dropping. Also, I highly advise running this on a GPU.

In [55]:
epochs = 1
# Save every N iterations
save_every_n = 200

model = CharRNN(len(vocab), batch_size=batch_size, num_steps=num_steps,
                lstm_size=lstm_size, num_layers=num_layers, 
                learning_rate=learning_rate)

saver = tf.train.Saver(max_to_keep=100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    # Use the line below to load a checkpoint and resume training
    #saver.restore(sess, 'checkpoints/______.ckpt')
    counter = 0
    for e in range(epochs):
        # Train network
        new_state = sess.run(model.initial_state)
        loss = 0
        for x, y in get_batches(encoded, batch_size, num_steps):
            counter += 1
            start = time.time()
            feed = {model.inputs: x,
                    model.targets: y,
                    model.keep_prob: keep_prob,
                    model.initial_state: new_state}
            batch_loss, new_state, _ = sess.run([model.loss, 
                                                 model.final_state, 
                                                 model.optimizer], 
                                                 feed_dict=feed)
            
            end = time.time()
            print('Epoch: {}/{}... '.format(e+1, epochs),
                  'Training Step: {}... '.format(counter),
                  'Training loss: {:.4f}... '.format(batch_loss),
                  '{:.4f} sec/batch'.format((end-start)))
        
            if (counter % save_every_n == 0):
                saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))
    
    saver.save(sess, "checkpoints/i{}_l{}.ckpt".format(counter, lstm_size))

Epoch: 1/1...  Training Step: 1...  Training loss: 4.4201...  0.0890 sec/batch
Epoch: 1/1...  Training Step: 2...  Training loss: 4.2995...  0.0640 sec/batch
Epoch: 1/1...  Training Step: 3...  Training loss: 3.5504...  0.0600 sec/batch
Epoch: 1/1...  Training Step: 4...  Training loss: 3.4359...  0.0650 sec/batch
Epoch: 1/1...  Training Step: 5...  Training loss: 3.2074...  0.0750 sec/batch
Epoch: 1/1...  Training Step: 6...  Training loss: 3.3657...  0.0640 sec/batch
Epoch: 1/1...  Training Step: 7...  Training loss: 3.2304...  0.1010 sec/batch
Epoch: 1/1...  Training Step: 8...  Training loss: 3.2128...  0.0660 sec/batch
Epoch: 1/1...  Training Step: 9...  Training loss: 3.2455...  0.0690 sec/batch
Epoch: 1/1...  Training Step: 10...  Training loss: 3.2552...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 11...  Training loss: 3.2810...  0.0720 sec/batch
Epoch: 1/1...  Training Step: 12...  Training loss: 3.1599...  0.0650 sec/batch
Epoch: 1/1...  Training Step: 13...  Training los

Epoch: 1/1...  Training Step: 104...  Training loss: 2.5941...  0.1030 sec/batch
Epoch: 1/1...  Training Step: 105...  Training loss: 2.7538...  0.0760 sec/batch
Epoch: 1/1...  Training Step: 106...  Training loss: 2.8360...  0.0680 sec/batch
Epoch: 1/1...  Training Step: 107...  Training loss: 2.7185...  0.0650 sec/batch
Epoch: 1/1...  Training Step: 108...  Training loss: 2.6973...  0.0730 sec/batch
Epoch: 1/1...  Training Step: 109...  Training loss: 2.6930...  0.0680 sec/batch
Epoch: 1/1...  Training Step: 110...  Training loss: 2.7946...  0.0760 sec/batch
Epoch: 1/1...  Training Step: 111...  Training loss: 2.6153...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 112...  Training loss: 2.7011...  0.0650 sec/batch
Epoch: 1/1...  Training Step: 113...  Training loss: 2.6874...  0.0810 sec/batch
Epoch: 1/1...  Training Step: 114...  Training loss: 2.5626...  0.0710 sec/batch
Epoch: 1/1...  Training Step: 115...  Training loss: 2.7391...  0.0870 sec/batch
Epoch: 1/1...  Training Step

Epoch: 1/1...  Training Step: 207...  Training loss: 2.4306...  0.0800 sec/batch
Epoch: 1/1...  Training Step: 208...  Training loss: 2.4613...  0.0810 sec/batch
Epoch: 1/1...  Training Step: 209...  Training loss: 2.4564...  0.0640 sec/batch
Epoch: 1/1...  Training Step: 210...  Training loss: 2.3564...  0.0740 sec/batch
Epoch: 1/1...  Training Step: 211...  Training loss: 2.3852...  0.0740 sec/batch
Epoch: 1/1...  Training Step: 212...  Training loss: 2.4432...  0.0740 sec/batch
Epoch: 1/1...  Training Step: 213...  Training loss: 2.4738...  0.0660 sec/batch
Epoch: 1/1...  Training Step: 214...  Training loss: 2.4563...  0.1040 sec/batch
Epoch: 1/1...  Training Step: 215...  Training loss: 2.4471...  0.0690 sec/batch
Epoch: 1/1...  Training Step: 216...  Training loss: 2.4077...  0.0800 sec/batch
Epoch: 1/1...  Training Step: 217...  Training loss: 2.4990...  0.0730 sec/batch
Epoch: 1/1...  Training Step: 218...  Training loss: 2.4191...  0.0620 sec/batch
Epoch: 1/1...  Training Step

Epoch: 1/1...  Training Step: 311...  Training loss: 2.3866...  0.0750 sec/batch
Epoch: 1/1...  Training Step: 312...  Training loss: 2.2398...  0.0660 sec/batch
Epoch: 1/1...  Training Step: 313...  Training loss: 2.2634...  0.0720 sec/batch
Epoch: 1/1...  Training Step: 314...  Training loss: 2.3144...  0.1110 sec/batch
Epoch: 1/1...  Training Step: 315...  Training loss: 2.3238...  0.1030 sec/batch
Epoch: 1/1...  Training Step: 316...  Training loss: 2.3371...  0.0810 sec/batch
Epoch: 1/1...  Training Step: 317...  Training loss: 2.3981...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 318...  Training loss: 2.3626...  0.0780 sec/batch
Epoch: 1/1...  Training Step: 319...  Training loss: 2.3133...  0.0670 sec/batch
Epoch: 1/1...  Training Step: 320...  Training loss: 2.3218...  0.0690 sec/batch
Epoch: 1/1...  Training Step: 321...  Training loss: 2.2870...  0.0720 sec/batch
Epoch: 1/1...  Training Step: 322...  Training loss: 2.2061...  0.0780 sec/batch
Epoch: 1/1...  Training Step

Epoch: 1/1...  Training Step: 415...  Training loss: 2.2148...  0.0800 sec/batch
Epoch: 1/1...  Training Step: 416...  Training loss: 2.1817...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 417...  Training loss: 2.2602...  0.0790 sec/batch
Epoch: 1/1...  Training Step: 418...  Training loss: 2.1686...  0.0990 sec/batch
Epoch: 1/1...  Training Step: 419...  Training loss: 2.1553...  0.0740 sec/batch
Epoch: 1/1...  Training Step: 420...  Training loss: 2.2553...  0.0730 sec/batch
Epoch: 1/1...  Training Step: 421...  Training loss: 2.2616...  0.0740 sec/batch
Epoch: 1/1...  Training Step: 422...  Training loss: 2.2697...  0.0740 sec/batch
Epoch: 1/1...  Training Step: 423...  Training loss: 2.3228...  0.0780 sec/batch
Epoch: 1/1...  Training Step: 424...  Training loss: 2.1528...  0.1000 sec/batch
Epoch: 1/1...  Training Step: 425...  Training loss: 2.2212...  0.0740 sec/batch
Epoch: 1/1...  Training Step: 426...  Training loss: 2.2409...  0.0720 sec/batch
Epoch: 1/1...  Training Step

Epoch: 1/1...  Training Step: 517...  Training loss: 2.2518...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 518...  Training loss: 2.1229...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 519...  Training loss: 2.1480...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 520...  Training loss: 2.1680...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 521...  Training loss: 2.0650...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 522...  Training loss: 2.2142...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 523...  Training loss: 2.1949...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 524...  Training loss: 2.2087...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 525...  Training loss: 2.0895...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 526...  Training loss: 2.1192...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 527...  Training loss: 2.1270...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 528...  Training loss: 2.2034...  0.0980 sec/batch
Epoch: 1/1...  Training Step

Epoch: 1/1...  Training Step: 619...  Training loss: 2.0403...  0.1110 sec/batch
Epoch: 1/1...  Training Step: 620...  Training loss: 2.0206...  0.0990 sec/batch
Epoch: 1/1...  Training Step: 621...  Training loss: 1.9932...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 622...  Training loss: 2.1204...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 623...  Training loss: 2.1072...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 624...  Training loss: 2.1192...  0.0890 sec/batch
Epoch: 1/1...  Training Step: 625...  Training loss: 2.0450...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 626...  Training loss: 2.0647...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 627...  Training loss: 2.1002...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 628...  Training loss: 2.0464...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 629...  Training loss: 2.0880...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 630...  Training loss: 2.2654...  0.0990 sec/batch
Epoch: 1/1...  Training Step

Epoch: 1/1...  Training Step: 721...  Training loss: 2.1239...  0.1100 sec/batch
Epoch: 1/1...  Training Step: 722...  Training loss: 1.9848...  0.1060 sec/batch
Epoch: 1/1...  Training Step: 723...  Training loss: 2.1836...  0.1040 sec/batch
Epoch: 1/1...  Training Step: 724...  Training loss: 2.1135...  0.1070 sec/batch
Epoch: 1/1...  Training Step: 725...  Training loss: 2.0425...  0.1040 sec/batch
Epoch: 1/1...  Training Step: 726...  Training loss: 2.0610...  0.1070 sec/batch
Epoch: 1/1...  Training Step: 727...  Training loss: 2.0543...  0.1060 sec/batch
Epoch: 1/1...  Training Step: 728...  Training loss: 2.0638...  0.1150 sec/batch
Epoch: 1/1...  Training Step: 729...  Training loss: 1.9824...  0.1060 sec/batch
Epoch: 1/1...  Training Step: 730...  Training loss: 2.0601...  0.1040 sec/batch
Epoch: 1/1...  Training Step: 731...  Training loss: 2.2384...  0.1040 sec/batch
Epoch: 1/1...  Training Step: 732...  Training loss: 2.0355...  0.1050 sec/batch
Epoch: 1/1...  Training Step

Epoch: 1/1...  Training Step: 823...  Training loss: 2.0073...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 824...  Training loss: 2.0212...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 825...  Training loss: 2.0248...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 826...  Training loss: 2.0611...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 827...  Training loss: 2.0191...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 828...  Training loss: 2.1417...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 829...  Training loss: 2.1389...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 830...  Training loss: 2.0393...  0.1080 sec/batch
Epoch: 1/1...  Training Step: 831...  Training loss: 2.1172...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 832...  Training loss: 2.0979...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 833...  Training loss: 2.0152...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 834...  Training loss: 2.0728...  0.0940 sec/batch
Epoch: 1/1...  Training Step

Epoch: 1/1...  Training Step: 924...  Training loss: 2.0025...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 925...  Training loss: 2.0178...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 926...  Training loss: 2.0414...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 927...  Training loss: 2.0188...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 928...  Training loss: 2.0593...  0.0890 sec/batch
Epoch: 1/1...  Training Step: 929...  Training loss: 2.0202...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 930...  Training loss: 2.0296...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 931...  Training loss: 2.1035...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 932...  Training loss: 1.9932...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 933...  Training loss: 1.9908...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 934...  Training loss: 2.0050...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 935...  Training loss: 2.0005...  0.0900 sec/batch
Epoch: 1/1...  Training Step

Epoch: 1/1...  Training Step: 1026...  Training loss: 2.1365...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 1027...  Training loss: 2.0304...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 1028...  Training loss: 1.9797...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 1029...  Training loss: 2.0439...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 1030...  Training loss: 2.0346...  0.0990 sec/batch
Epoch: 1/1...  Training Step: 1031...  Training loss: 1.9886...  0.1090 sec/batch
Epoch: 1/1...  Training Step: 1032...  Training loss: 1.9291...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 1033...  Training loss: 1.9964...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 1034...  Training loss: 2.0086...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 1035...  Training loss: 2.0859...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 1036...  Training loss: 2.1325...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 1037...  Training loss: 1.9441...  0.0920 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 1126...  Training loss: 2.0027...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 1127...  Training loss: 2.0091...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 1128...  Training loss: 1.9468...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 1129...  Training loss: 1.9776...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 1130...  Training loss: 1.9856...  0.0890 sec/batch
Epoch: 1/1...  Training Step: 1131...  Training loss: 1.9768...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 1132...  Training loss: 1.8330...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 1133...  Training loss: 1.9076...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 1134...  Training loss: 2.0885...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 1135...  Training loss: 1.8970...  0.1000 sec/batch
Epoch: 1/1...  Training Step: 1136...  Training loss: 2.0964...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 1137...  Training loss: 2.0526...  0.0910 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 1226...  Training loss: 1.9677...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 1227...  Training loss: 2.0777...  0.1030 sec/batch
Epoch: 1/1...  Training Step: 1228...  Training loss: 2.0302...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 1229...  Training loss: 1.9207...  0.1010 sec/batch
Epoch: 1/1...  Training Step: 1230...  Training loss: 2.0152...  0.0850 sec/batch
Epoch: 1/1...  Training Step: 1231...  Training loss: 1.8669...  0.0890 sec/batch
Epoch: 1/1...  Training Step: 1232...  Training loss: 2.0693...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 1233...  Training loss: 2.0061...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 1234...  Training loss: 2.0406...  0.0860 sec/batch
Epoch: 1/1...  Training Step: 1235...  Training loss: 1.9399...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 1236...  Training loss: 1.9649...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 1237...  Training loss: 1.9801...  0.0880 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 1327...  Training loss: 2.0551...  0.0870 sec/batch
Epoch: 1/1...  Training Step: 1328...  Training loss: 1.9162...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 1329...  Training loss: 2.0090...  0.1050 sec/batch
Epoch: 1/1...  Training Step: 1330...  Training loss: 2.0329...  0.1020 sec/batch
Epoch: 1/1...  Training Step: 1331...  Training loss: 2.0490...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 1332...  Training loss: 1.9183...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 1333...  Training loss: 1.9339...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 1334...  Training loss: 2.0366...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 1335...  Training loss: 1.8483...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 1336...  Training loss: 1.9772...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 1337...  Training loss: 1.9152...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 1338...  Training loss: 1.9390...  0.0920 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 1427...  Training loss: 1.9007...  0.1030 sec/batch
Epoch: 1/1...  Training Step: 1428...  Training loss: 1.9967...  0.1020 sec/batch
Epoch: 1/1...  Training Step: 1429...  Training loss: 2.0480...  0.0870 sec/batch
Epoch: 1/1...  Training Step: 1430...  Training loss: 2.0415...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 1431...  Training loss: 1.9071...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 1432...  Training loss: 1.9968...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 1433...  Training loss: 2.1685...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 1434...  Training loss: 1.9233...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 1435...  Training loss: 2.0207...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 1436...  Training loss: 1.9632...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 1437...  Training loss: 1.9446...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 1438...  Training loss: 1.9923...  0.0970 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 1528...  Training loss: 1.9473...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 1529...  Training loss: 2.0514...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 1530...  Training loss: 1.9575...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 1531...  Training loss: 2.0146...  0.0990 sec/batch
Epoch: 1/1...  Training Step: 1532...  Training loss: 2.0502...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 1533...  Training loss: 2.0009...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 1534...  Training loss: 1.9460...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 1535...  Training loss: 2.0487...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 1536...  Training loss: 1.8766...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 1537...  Training loss: 1.8981...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 1538...  Training loss: 1.9663...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 1539...  Training loss: 2.1311...  0.0900 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 1628...  Training loss: 2.0261...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 1629...  Training loss: 2.0083...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 1630...  Training loss: 1.9794...  0.1250 sec/batch
Epoch: 1/1...  Training Step: 1631...  Training loss: 1.9268...  0.1270 sec/batch
Epoch: 1/1...  Training Step: 1632...  Training loss: 1.7827...  0.1150 sec/batch
Epoch: 1/1...  Training Step: 1633...  Training loss: 1.9609...  0.1050 sec/batch
Epoch: 1/1...  Training Step: 1634...  Training loss: 1.8860...  0.1010 sec/batch
Epoch: 1/1...  Training Step: 1635...  Training loss: 1.8503...  0.1090 sec/batch
Epoch: 1/1...  Training Step: 1636...  Training loss: 2.0248...  0.1020 sec/batch
Epoch: 1/1...  Training Step: 1637...  Training loss: 1.9402...  0.1050 sec/batch
Epoch: 1/1...  Training Step: 1638...  Training loss: 1.8063...  0.1170 sec/batch
Epoch: 1/1...  Training Step: 1639...  Training loss: 1.9378...  0.1150 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 1728...  Training loss: 1.9039...  0.1010 sec/batch
Epoch: 1/1...  Training Step: 1729...  Training loss: 1.9196...  0.1090 sec/batch
Epoch: 1/1...  Training Step: 1730...  Training loss: 1.8349...  0.1030 sec/batch
Epoch: 1/1...  Training Step: 1731...  Training loss: 1.9045...  0.1070 sec/batch
Epoch: 1/1...  Training Step: 1732...  Training loss: 2.0199...  0.1100 sec/batch
Epoch: 1/1...  Training Step: 1733...  Training loss: 2.0531...  0.1040 sec/batch
Epoch: 1/1...  Training Step: 1734...  Training loss: 2.1146...  0.1190 sec/batch
Epoch: 1/1...  Training Step: 1735...  Training loss: 2.0085...  0.1060 sec/batch
Epoch: 1/1...  Training Step: 1736...  Training loss: 1.9207...  0.1160 sec/batch
Epoch: 1/1...  Training Step: 1737...  Training loss: 1.9037...  0.1010 sec/batch
Epoch: 1/1...  Training Step: 1738...  Training loss: 1.9683...  0.1100 sec/batch
Epoch: 1/1...  Training Step: 1739...  Training loss: 1.9411...  0.1060 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 1828...  Training loss: 1.8986...  0.0970 sec/batch
Epoch: 1/1...  Training Step: 1829...  Training loss: 2.0107...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 1830...  Training loss: 1.8783...  0.0970 sec/batch
Epoch: 1/1...  Training Step: 1831...  Training loss: 1.9934...  0.0990 sec/batch
Epoch: 1/1...  Training Step: 1832...  Training loss: 1.9410...  0.0890 sec/batch
Epoch: 1/1...  Training Step: 1833...  Training loss: 1.9285...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 1834...  Training loss: 1.9390...  0.0860 sec/batch
Epoch: 1/1...  Training Step: 1835...  Training loss: 1.8792...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 1836...  Training loss: 1.9694...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 1837...  Training loss: 1.9609...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 1838...  Training loss: 1.8647...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 1839...  Training loss: 1.8853...  0.0880 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 1928...  Training loss: 1.9895...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 1929...  Training loss: 1.9300...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 1930...  Training loss: 1.9284...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 1931...  Training loss: 1.8443...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 1932...  Training loss: 1.8964...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 1933...  Training loss: 1.8827...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 1934...  Training loss: 2.1173...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 1935...  Training loss: 1.9206...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 1936...  Training loss: 1.9874...  0.0870 sec/batch
Epoch: 1/1...  Training Step: 1937...  Training loss: 2.0351...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 1938...  Training loss: 2.1977...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 1939...  Training loss: 1.9843...  0.0920 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 2029...  Training loss: 1.9949...  0.0970 sec/batch
Epoch: 1/1...  Training Step: 2030...  Training loss: 1.7551...  0.1010 sec/batch
Epoch: 1/1...  Training Step: 2031...  Training loss: 1.7890...  0.1020 sec/batch
Epoch: 1/1...  Training Step: 2032...  Training loss: 1.8891...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 2033...  Training loss: 1.8882...  0.1040 sec/batch
Epoch: 1/1...  Training Step: 2034...  Training loss: 1.9200...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 2035...  Training loss: 1.8333...  0.0990 sec/batch
Epoch: 1/1...  Training Step: 2036...  Training loss: 1.9034...  0.1040 sec/batch
Epoch: 1/1...  Training Step: 2037...  Training loss: 1.7253...  0.1080 sec/batch
Epoch: 1/1...  Training Step: 2038...  Training loss: 1.8788...  0.0890 sec/batch
Epoch: 1/1...  Training Step: 2039...  Training loss: 1.8625...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 2040...  Training loss: 2.0250...  0.0990 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 2131...  Training loss: 1.8329...  0.0800 sec/batch
Epoch: 1/1...  Training Step: 2132...  Training loss: 1.8055...  0.0760 sec/batch
Epoch: 1/1...  Training Step: 2133...  Training loss: 1.9543...  0.0800 sec/batch
Epoch: 1/1...  Training Step: 2134...  Training loss: 1.9388...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 2135...  Training loss: 1.8341...  0.0850 sec/batch
Epoch: 1/1...  Training Step: 2136...  Training loss: 1.8336...  0.0840 sec/batch
Epoch: 1/1...  Training Step: 2137...  Training loss: 1.8914...  0.0790 sec/batch
Epoch: 1/1...  Training Step: 2138...  Training loss: 1.8991...  0.0790 sec/batch
Epoch: 1/1...  Training Step: 2139...  Training loss: 1.9173...  0.0840 sec/batch
Epoch: 1/1...  Training Step: 2140...  Training loss: 1.9428...  0.0770 sec/batch
Epoch: 1/1...  Training Step: 2141...  Training loss: 1.8791...  0.0840 sec/batch
Epoch: 1/1...  Training Step: 2142...  Training loss: 1.9769...  0.0770 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 2233...  Training loss: 1.8569...  0.1010 sec/batch
Epoch: 1/1...  Training Step: 2234...  Training loss: 1.8885...  0.0870 sec/batch
Epoch: 1/1...  Training Step: 2235...  Training loss: 1.7778...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 2236...  Training loss: 1.6420...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 2237...  Training loss: 1.8609...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 2238...  Training loss: 1.7540...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 2239...  Training loss: 1.8985...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 2240...  Training loss: 2.1297...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 2241...  Training loss: 2.0347...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 2242...  Training loss: 1.9118...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 2243...  Training loss: 1.9410...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 2244...  Training loss: 1.9193...  0.0880 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 2333...  Training loss: 1.7301...  0.0870 sec/batch
Epoch: 1/1...  Training Step: 2334...  Training loss: 1.7924...  0.1460 sec/batch
Epoch: 1/1...  Training Step: 2335...  Training loss: 1.8441...  0.1170 sec/batch
Epoch: 1/1...  Training Step: 2336...  Training loss: 1.8809...  0.1170 sec/batch
Epoch: 1/1...  Training Step: 2337...  Training loss: 2.0247...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 2338...  Training loss: 2.0768...  0.1000 sec/batch
Epoch: 1/1...  Training Step: 2339...  Training loss: 1.9267...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 2340...  Training loss: 1.9400...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 2341...  Training loss: 1.8726...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 2342...  Training loss: 1.7908...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 2343...  Training loss: 1.8861...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 2344...  Training loss: 1.8440...  0.0900 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 2434...  Training loss: 1.8890...  0.0970 sec/batch
Epoch: 1/1...  Training Step: 2435...  Training loss: 1.7565...  0.1030 sec/batch
Epoch: 1/1...  Training Step: 2436...  Training loss: 1.9508...  0.1060 sec/batch
Epoch: 1/1...  Training Step: 2437...  Training loss: 1.8010...  0.1200 sec/batch
Epoch: 1/1...  Training Step: 2438...  Training loss: 1.9495...  0.2000 sec/batch
Epoch: 1/1...  Training Step: 2439...  Training loss: 1.9147...  0.1230 sec/batch
Epoch: 1/1...  Training Step: 2440...  Training loss: 1.9326...  0.1050 sec/batch
Epoch: 1/1...  Training Step: 2441...  Training loss: 1.8213...  0.1010 sec/batch
Epoch: 1/1...  Training Step: 2442...  Training loss: 1.8656...  0.1290 sec/batch
Epoch: 1/1...  Training Step: 2443...  Training loss: 1.8079...  0.1290 sec/batch
Epoch: 1/1...  Training Step: 2444...  Training loss: 1.9407...  0.1020 sec/batch
Epoch: 1/1...  Training Step: 2445...  Training loss: 1.8652...  0.1120 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 2535...  Training loss: 1.9031...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 2536...  Training loss: 1.8683...  0.0860 sec/batch
Epoch: 1/1...  Training Step: 2537...  Training loss: 1.8557...  0.0870 sec/batch
Epoch: 1/1...  Training Step: 2538...  Training loss: 1.9047...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 2539...  Training loss: 1.9498...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 2540...  Training loss: 1.9214...  0.0970 sec/batch
Epoch: 1/1...  Training Step: 2541...  Training loss: 1.9036...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 2542...  Training loss: 1.8988...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 2543...  Training loss: 1.7550...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 2544...  Training loss: 1.9847...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 2545...  Training loss: 1.8069...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 2546...  Training loss: 1.7970...  0.0910 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 2635...  Training loss: 1.7738...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 2636...  Training loss: 1.8874...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 2637...  Training loss: 1.9443...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 2638...  Training loss: 1.7721...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 2639...  Training loss: 1.9222...  0.0970 sec/batch
Epoch: 1/1...  Training Step: 2640...  Training loss: 1.8230...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 2641...  Training loss: 1.9393...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 2642...  Training loss: 1.8067...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 2643...  Training loss: 1.7631...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 2644...  Training loss: 1.8401...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 2645...  Training loss: 1.9839...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 2646...  Training loss: 1.8584...  0.0900 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 2735...  Training loss: 1.7642...  0.1040 sec/batch
Epoch: 1/1...  Training Step: 2736...  Training loss: 1.8936...  0.1080 sec/batch
Epoch: 1/1...  Training Step: 2737...  Training loss: 1.7649...  0.1070 sec/batch
Epoch: 1/1...  Training Step: 2738...  Training loss: 1.8744...  0.1020 sec/batch
Epoch: 1/1...  Training Step: 2739...  Training loss: 2.0412...  0.0990 sec/batch
Epoch: 1/1...  Training Step: 2740...  Training loss: 1.8120...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 2741...  Training loss: 1.8638...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 2742...  Training loss: 1.9690...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 2743...  Training loss: 2.0136...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 2744...  Training loss: 1.8906...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 2745...  Training loss: 1.8937...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 2746...  Training loss: 2.0664...  0.0930 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 2836...  Training loss: 2.0253...  0.1030 sec/batch
Epoch: 1/1...  Training Step: 2837...  Training loss: 1.9447...  0.1150 sec/batch
Epoch: 1/1...  Training Step: 2838...  Training loss: 1.9136...  0.1110 sec/batch
Epoch: 1/1...  Training Step: 2839...  Training loss: 1.9431...  0.1130 sec/batch
Epoch: 1/1...  Training Step: 2840...  Training loss: 1.8681...  0.1050 sec/batch
Epoch: 1/1...  Training Step: 2841...  Training loss: 2.0042...  0.1090 sec/batch
Epoch: 1/1...  Training Step: 2842...  Training loss: 1.9212...  0.1010 sec/batch
Epoch: 1/1...  Training Step: 2843...  Training loss: 1.6883...  0.1030 sec/batch
Epoch: 1/1...  Training Step: 2844...  Training loss: 1.7395...  0.1120 sec/batch
Epoch: 1/1...  Training Step: 2845...  Training loss: 1.8376...  0.1000 sec/batch
Epoch: 1/1...  Training Step: 2846...  Training loss: 1.8260...  0.1060 sec/batch
Epoch: 1/1...  Training Step: 2847...  Training loss: 1.8967...  0.1050 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 2937...  Training loss: 1.8819...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 2938...  Training loss: 1.8094...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 2939...  Training loss: 1.7993...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 2940...  Training loss: 1.8773...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 2941...  Training loss: 1.9688...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 2942...  Training loss: 2.0157...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 2943...  Training loss: 1.9084...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 2944...  Training loss: 1.7862...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 2945...  Training loss: 1.7622...  0.0870 sec/batch
Epoch: 1/1...  Training Step: 2946...  Training loss: 1.8966...  0.0920 sec/batch
Epoch: 1/1...  Training Step: 2947...  Training loss: 1.8440...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 2948...  Training loss: 1.7315...  0.0930 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 3038...  Training loss: 1.9911...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 3039...  Training loss: 1.8028...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 3040...  Training loss: 2.0218...  0.0870 sec/batch
Epoch: 1/1...  Training Step: 3041...  Training loss: 1.7987...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 3042...  Training loss: 1.8217...  0.0870 sec/batch
Epoch: 1/1...  Training Step: 3043...  Training loss: 1.8794...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 3044...  Training loss: 1.9021...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 3045...  Training loss: 1.8228...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 3046...  Training loss: 1.8932...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 3047...  Training loss: 1.7376...  0.0970 sec/batch
Epoch: 1/1...  Training Step: 3048...  Training loss: 2.0282...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 3049...  Training loss: 1.9004...  0.0930 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 3138...  Training loss: 1.8155...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 3139...  Training loss: 1.8453...  0.1040 sec/batch
Epoch: 1/1...  Training Step: 3140...  Training loss: 1.9757...  0.1190 sec/batch
Epoch: 1/1...  Training Step: 3141...  Training loss: 1.8911...  0.1030 sec/batch
Epoch: 1/1...  Training Step: 3142...  Training loss: 1.7130...  0.1150 sec/batch
Epoch: 1/1...  Training Step: 3143...  Training loss: 1.9279...  0.1150 sec/batch
Epoch: 1/1...  Training Step: 3144...  Training loss: 1.7414...  0.1000 sec/batch
Epoch: 1/1...  Training Step: 3145...  Training loss: 1.8933...  0.1010 sec/batch
Epoch: 1/1...  Training Step: 3146...  Training loss: 1.8419...  0.0870 sec/batch
Epoch: 1/1...  Training Step: 3147...  Training loss: 1.8351...  0.1040 sec/batch
Epoch: 1/1...  Training Step: 3148...  Training loss: 1.8774...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 3149...  Training loss: 1.8075...  0.0920 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 3239...  Training loss: 1.8108...  0.0970 sec/batch
Epoch: 1/1...  Training Step: 3240...  Training loss: 1.7826...  0.0870 sec/batch
Epoch: 1/1...  Training Step: 3241...  Training loss: 1.9128...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 3242...  Training loss: 1.7289...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 3243...  Training loss: 1.8874...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 3244...  Training loss: 1.9028...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 3245...  Training loss: 1.9083...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 3246...  Training loss: 1.9248...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 3247...  Training loss: 1.8900...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 3248...  Training loss: 1.8848...  0.0970 sec/batch
Epoch: 1/1...  Training Step: 3249...  Training loss: 1.9763...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 3250...  Training loss: 1.8170...  0.0990 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 3339...  Training loss: 1.7238...  0.0930 sec/batch
Epoch: 1/1...  Training Step: 3340...  Training loss: 1.8352...  0.1020 sec/batch
Epoch: 1/1...  Training Step: 3341...  Training loss: 1.8887...  0.0970 sec/batch
Epoch: 1/1...  Training Step: 3342...  Training loss: 1.8716...  0.0870 sec/batch
Epoch: 1/1...  Training Step: 3343...  Training loss: 1.8453...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 3344...  Training loss: 1.8605...  0.1000 sec/batch
Epoch: 1/1...  Training Step: 3345...  Training loss: 1.8167...  0.0990 sec/batch
Epoch: 1/1...  Training Step: 3346...  Training loss: 1.9534...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 3347...  Training loss: 1.9808...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 3348...  Training loss: 1.9309...  0.1000 sec/batch
Epoch: 1/1...  Training Step: 3349...  Training loss: 2.0291...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 3350...  Training loss: 1.7427...  0.0930 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 3439...  Training loss: 2.0027...  0.1010 sec/batch
Epoch: 1/1...  Training Step: 3440...  Training loss: 1.9866...  0.0970 sec/batch
Epoch: 1/1...  Training Step: 3441...  Training loss: 1.8265...  0.1030 sec/batch
Epoch: 1/1...  Training Step: 3442...  Training loss: 1.7361...  0.0980 sec/batch
Epoch: 1/1...  Training Step: 3443...  Training loss: 1.8121...  0.0960 sec/batch
Epoch: 1/1...  Training Step: 3444...  Training loss: 1.9027...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 3445...  Training loss: 1.8585...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 3446...  Training loss: 1.8375...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 3447...  Training loss: 1.9111...  0.0970 sec/batch
Epoch: 1/1...  Training Step: 3448...  Training loss: 1.7610...  0.1000 sec/batch
Epoch: 1/1...  Training Step: 3449...  Training loss: 1.8417...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 3450...  Training loss: 1.8109...  0.0980 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 3539...  Training loss: 1.8848...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 3540...  Training loss: 1.8163...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 3541...  Training loss: 1.9334...  0.0890 sec/batch
Epoch: 1/1...  Training Step: 3542...  Training loss: 1.8372...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 3543...  Training loss: 1.6860...  0.0890 sec/batch
Epoch: 1/1...  Training Step: 3544...  Training loss: 1.7746...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 3545...  Training loss: 1.8694...  0.0890 sec/batch
Epoch: 1/1...  Training Step: 3546...  Training loss: 1.6886...  0.0910 sec/batch
Epoch: 1/1...  Training Step: 3547...  Training loss: 1.8041...  0.0970 sec/batch
Epoch: 1/1...  Training Step: 3548...  Training loss: 1.6908...  0.0880 sec/batch
Epoch: 1/1...  Training Step: 3549...  Training loss: 1.7648...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 3550...  Training loss: 1.9134...  0.0940 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 3639...  Training loss: 1.8851...  0.1080 sec/batch
Epoch: 1/1...  Training Step: 3640...  Training loss: 1.7756...  0.1100 sec/batch
Epoch: 1/1...  Training Step: 3641...  Training loss: 1.9945...  0.1120 sec/batch
Epoch: 1/1...  Training Step: 3642...  Training loss: 1.9429...  0.0950 sec/batch
Epoch: 1/1...  Training Step: 3643...  Training loss: 2.1339...  0.1030 sec/batch
Epoch: 1/1...  Training Step: 3644...  Training loss: 1.9565...  0.1010 sec/batch
Epoch: 1/1...  Training Step: 3645...  Training loss: 1.8609...  0.1110 sec/batch
Epoch: 1/1...  Training Step: 3646...  Training loss: 1.6464...  0.1010 sec/batch
Epoch: 1/1...  Training Step: 3647...  Training loss: 1.9331...  0.1100 sec/batch
Epoch: 1/1...  Training Step: 3648...  Training loss: 2.0139...  0.1120 sec/batch
Epoch: 1/1...  Training Step: 3649...  Training loss: 1.7701...  0.1060 sec/batch
Epoch: 1/1...  Training Step: 3650...  Training loss: 1.9648...  0.1720 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 3740...  Training loss: 1.8496...  0.0990 sec/batch
Epoch: 1/1...  Training Step: 3741...  Training loss: 1.9582...  0.0940 sec/batch
Epoch: 1/1...  Training Step: 3742...  Training loss: 2.0652...  0.0840 sec/batch
Epoch: 1/1...  Training Step: 3743...  Training loss: 1.9571...  0.0860 sec/batch
Epoch: 1/1...  Training Step: 3744...  Training loss: 1.9192...  0.0890 sec/batch
Epoch: 1/1...  Training Step: 3745...  Training loss: 1.7765...  0.0830 sec/batch
Epoch: 1/1...  Training Step: 3746...  Training loss: 2.1402...  0.0850 sec/batch
Epoch: 1/1...  Training Step: 3747...  Training loss: 1.9004...  0.0900 sec/batch
Epoch: 1/1...  Training Step: 3748...  Training loss: 2.1165...  0.0770 sec/batch
Epoch: 1/1...  Training Step: 3749...  Training loss: 1.7830...  0.0820 sec/batch
Epoch: 1/1...  Training Step: 3750...  Training loss: 1.8536...  0.2370 sec/batch
Epoch: 1/1...  Training Step: 3751...  Training loss: 1.9488...  0.2320 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 3841...  Training loss: 1.9037...  0.0750 sec/batch
Epoch: 1/1...  Training Step: 3842...  Training loss: 2.0230...  0.0730 sec/batch
Epoch: 1/1...  Training Step: 3843...  Training loss: 2.1333...  0.0720 sec/batch
Epoch: 1/1...  Training Step: 3844...  Training loss: 2.1630...  0.0740 sec/batch
Epoch: 1/1...  Training Step: 3845...  Training loss: 2.0088...  0.0720 sec/batch
Epoch: 1/1...  Training Step: 3846...  Training loss: 1.9401...  0.0710 sec/batch
Epoch: 1/1...  Training Step: 3847...  Training loss: 1.8319...  0.0710 sec/batch
Epoch: 1/1...  Training Step: 3848...  Training loss: 1.9111...  0.0710 sec/batch
Epoch: 1/1...  Training Step: 3849...  Training loss: 1.7453...  0.0700 sec/batch
Epoch: 1/1...  Training Step: 3850...  Training loss: 1.8123...  0.0720 sec/batch
Epoch: 1/1...  Training Step: 3851...  Training loss: 2.0638...  0.0720 sec/batch
Epoch: 1/1...  Training Step: 3852...  Training loss: 1.9536...  0.1070 sec/batch
Epoch: 1/1...  T

Epoch: 1/1...  Training Step: 3943...  Training loss: 1.8014...  0.0760 sec/batch
Epoch: 1/1...  Training Step: 3944...  Training loss: 1.7865...  0.0710 sec/batch
Epoch: 1/1...  Training Step: 3945...  Training loss: 1.8689...  0.0740 sec/batch
Epoch: 1/1...  Training Step: 3946...  Training loss: 2.0848...  0.0770 sec/batch
Epoch: 1/1...  Training Step: 3947...  Training loss: 1.9783...  0.0720 sec/batch
Epoch: 1/1...  Training Step: 3948...  Training loss: 1.9761...  0.0730 sec/batch
Epoch: 1/1...  Training Step: 3949...  Training loss: 1.8709...  0.0760 sec/batch
Epoch: 1/1...  Training Step: 3950...  Training loss: 1.7468...  0.0710 sec/batch
Epoch: 1/1...  Training Step: 3951...  Training loss: 1.8168...  0.0770 sec/batch
Epoch: 1/1...  Training Step: 3952...  Training loss: 1.7690...  0.0720 sec/batch
Epoch: 1/1...  Training Step: 3953...  Training loss: 1.8232...  0.0730 sec/batch
Epoch: 1/1...  Training Step: 3954...  Training loss: 1.9900...  0.0700 sec/batch
Epoch: 1/1...  T

#### Saved checkpoints

Read up on saving and loading checkpoints here: https://www.tensorflow.org/programmers_guide/variables

In [56]:
tf.train.get_checkpoint_state('checkpoints')

model_checkpoint_path: "checkpoints\\i3970_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i200_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i400_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i600_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i800_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1000_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1200_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1400_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1600_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i1800_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2000_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2200_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2400_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2600_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i2800_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i3000_l128.ckpt"
all_model_checkpoint_paths: "checkpoints\\i3200_l128.ckpt"
all_mo

## Sampling

Now that the network is trained, we'll can use it to generate new text. The idea is that we pass in a character, then the network will predict the next character. We can use the new one, to predict the next one. And we keep doing this to generate all new text. I also included some functionality to prime the network with some text by passing in a string and building up a state from that.

The network gives us predictions for each character. To reduce noise and make things a little less random, I'm going to only choose a new character from the top N most likely characters.



In [57]:
def pick_top_n(preds, vocab_size, top_n=5):
    p = np.squeeze(preds)
    p[np.argsort(p)[:-top_n]] = 0
    p = p / np.sum(p)
    c = np.random.choice(vocab_size, 1, p=p)[0]
    return c

In [58]:
def sample(checkpoint, n_samples, lstm_size, vocab_size, prime="The "):
    samples = [c for c in prime]
    model = CharRNN(len(vocab), lstm_size=lstm_size, sampling=True)
    saver = tf.train.Saver()
    with tf.Session() as sess:
        saver.restore(sess, checkpoint)
        new_state = sess.run(model.initial_state)
        for c in prime:
            x = np.zeros((1, 1))
            x[0,0] = vocab_to_int[c]
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

        c = pick_top_n(preds, len(vocab))
        samples.append(int_to_vocab[c])

        for i in range(n_samples):
            x[0,0] = c
            feed = {model.inputs: x,
                    model.keep_prob: 1.,
                    model.initial_state: new_state}
            preds, new_state = sess.run([model.prediction, model.final_state], 
                                         feed_dict=feed)

            c = pick_top_n(preds, len(vocab))
            samples.append(int_to_vocab[c])
        
    return ''.join(samples)

Here, pass in the path to a checkpoint and sample from the network.

In [59]:
tf.train.latest_checkpoint('checkpoints')

'checkpoints\\i3970_l128.ckpt'

In [60]:
checkpoint = tf.train.latest_checkpoint('checkpoints')
samp = sample(checkpoint, 2000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints\i3970_l128.ckpt
Fard here the olg all hers, houd of
they," she said that at and taw thrink of an and said.

"Who sillester.


.."

"All this and aneless whe
new on on had soul helray it."

"Bomas. This to tenged
a mans on him the composally to her saids a the
men innont to a teafhe oun talked and hoss that
his sontely to her
and sut to the low the stoman work in a sence.

"I not, but haskeling here and not sand that as. "I all the wouding to,
she were
compressely, and that had so notheds if the sorter, so not that it had becievinch ofen of the
mather, as had ofhing and where and to her he have her think to a meante, his and to then son anst times and her,
and to hove anywink thin out he to on tham she, had not to she shaps at his hands and and sest andss
to hers theen and ofh in,", as that sayitg her, the she haken his nos and at the cand to the so all her to
stell wicking to nime stepa and strooking alone of her, and a camirate to


In [61]:
checkpoint = 'checkpoints/i200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

INFO:tensorflow:Restoring parameters from checkpoints/i200_l512.ckpt


NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/i200_l512.ckpt
	 [[Node: save/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_3/tensor_names, save/RestoreV2_3/shape_and_slices)]]

Caused by op 'save/RestoreV2_3', defined at:
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 112, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\asyncio\base_events.py", line 1432, in _run_once
    handle._run()
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\ioloop.py", line 760, in _run_callback
    ret = callback()
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 536, in <lambda>
    self.io_loop.add_callback(lambda : self._handle_events(self.socket, 0))
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\tornado\stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-61-a2d1068e69fd>", line 2, in <module>
    samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
  File "<ipython-input-58-8693ad72bd2c>", line 4, in sample
    saver = tf.train.Saver()
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1056, in __init__
    self.build()
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 691, in build
    restore_sequentially, reshape)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\stha\AppData\Local\Continuum\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for checkpoints/i200_l512.ckpt
	 [[Node: save/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_3/tensor_names, save/RestoreV2_3/shape_and_slices)]]


In [ ]:
checkpoint = 'checkpoints/i600_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)

In [ ]:
checkpoint = 'checkpoints/i1200_l512.ckpt'
samp = sample(checkpoint, 1000, lstm_size, len(vocab), prime="Far")
print(samp)